/*  tb_trigger.v — acceptance testbench for cpsplus_trigger
    ========================================================

    Replays stimulus vectors generated by tb/gen_trigger_vectors.py from
    the project's validated software artifacts (Phase-0 latch traces,
    Phase-2 prototype event logs, directed corner cases) and checks:

      * the emitted verb-event sequence equals the golden log,
        frame-accurately (verb, track, gain, argw, argb, ctrl, sup);
      * `gate` is asserted during exactly the stimulus cycles flagged as
        suppressed handshake writes, and NEVER at any other time;
      * err_unsettled stays low.

    Vector formats: see gen_trigger_vectors.py header.
    Plusargs:  +CFG=<file> +TRIG=<file> +STIM=<file> +GOLD=<file> +NAME=<id>
               [+VCD=<file>]

    Each stimulus vector is driven as one 68K bus cycle: 6 clk active,
    6 clk idle (a real cycle is longer at the core's 96 MHz clock; the
    module only needs >= 1 idle clk between writes and >= 4 clk from a
    command-byte write to the handshake write for the lookup to settle).
*/
`timescale 1ns/1ps

module tb_trigger;

localparam TRIG_ROWS = 4608;
localparam CFG_LINES = 72;
localparam MAX_STIM  = 1<<17;
localparam MAX_GOLD  = 1<<13;

reg clk = 0;
always #5 clk = ~clk;

reg         rst;
reg  [23:1] addr;
reg  [15:0] dout;
reg  [ 1:0] dsn;
reg         rnw;
reg         cs;
wire        gate;
wire        evt_stb, evt_ctrl, evt_sup, err_unsettled;
wire [ 2:0] evt_verb;
wire [11:0] evt_track;
wire [ 6:0] evt_gain;
wire [15:0] evt_argw;
wire [ 7:0] evt_argb;
reg         cfg_we;
reg  [ 7:0] cfg_addr;
reg  [15:0] cfg_data;
reg         trig_we;
reg  [12:0] trig_addr;
reg  [31:0] trig_data;

cpsplus_trigger #(.TRIG_ROWS(TRIG_ROWS), .TRIG_AW(13)) uut (
    .rst        ( rst       ),
    .clk        ( clk       ),
    .cen        ( 1'b1      ),
    .addr       ( addr      ),
    .dout       ( dout      ),
    .dsn        ( dsn       ),
    .rnw        ( rnw       ),
    .cs         ( cs        ),
    .gate       ( gate      ),
    .evt_stb    ( evt_stb   ),
    .evt_verb   ( evt_verb  ),
    .evt_track  ( evt_track ),
    .evt_gain   ( evt_gain  ),
    .evt_argw   ( evt_argw  ),
    .evt_argb   ( evt_argb  ),
    .evt_ctrl   ( evt_ctrl  ),
    .evt_sup    ( evt_sup   ),
    .err_unsettled( err_unsettled ),
    .cfg_we     ( cfg_we    ),
    .cfg_addr   ( cfg_addr  ),
    .cfg_data   ( cfg_data  ),
    .trig_we    ( trig_we   ),
    .trig_addr  ( trig_addr ),
    .trig_data  ( trig_data )
);

reg [23:0] cfg_mem  [0:CFG_LINES-1];
reg [31:0] trig_mem [0:TRIG_ROWS-1];
reg [79:0] stim     [0:MAX_STIM-1];
reg [79:0] gold     [0:MAX_GOLD-1];

reg [8*200:1] fname, run_name, vcd_name;
integer n_stim, n_gold, i, errors, gates_seen, events_seen;

// ---- current-cycle bookkeeping shared with the monitor ----
reg         drive_act;      // a stimulus bus cycle is being driven
reg         exp_gate;       // that cycle expects the gate
reg  [19:0] cur_frame;
reg         gate_seen;
integer     gidx;

// continuous monitor: gate legality + event capture/compare
always @(posedge clk) begin
    if( !rst ) begin
        if( gate ) begin
            if( !drive_act || !exp_gate ) begin
                errors = errors + 1;
                $display("FAIL %0s: unexpected gate at t=%0t frame=%0d",
                         run_name, $time, cur_frame);
            end
            gate_seen = 1;
        end
        if( evt_stb ) begin
            events_seen = events_seen + 1;
            if( gidx >= n_gold ) begin
                errors = errors + 1;
                $display("FAIL %0s: extra event #%0d frame=%0d verb=%0d cmd track=%0d",
                         run_name, events_seen, cur_frame, evt_verb, evt_track);
            end else begin
                if( gold[gidx][79:60] !== cur_frame
                 || gold[gidx][59:56] !== {1'b0, evt_verb}
                 || gold[gidx][55:44] !== evt_track
                 || gold[gidx][43:36] !== {1'b0, evt_gain}
                 || gold[gidx][35:20] !== evt_argw
                 || gold[gidx][19:12] !== evt_argb
                 || gold[gidx][1]     !== evt_ctrl
                 || gold[gidx][0]     !== evt_sup ) begin
                    errors = errors + 1;
                    $display("FAIL %0s: event %0d mismatch", run_name, gidx);
                    $display("  got  frame=%0d verb=%0d track=%0d gain=%0d argw=%04x argb=%02x ctrl=%b sup=%b",
                        cur_frame, evt_verb, evt_track, evt_gain, evt_argw,
                        evt_argb, evt_ctrl, evt_sup);
                    $display("  want frame=%0d verb=%0d track=%0d gain=%0d argw=%04x argb=%02x ctrl=%b sup=%b",
                        gold[gidx][79:60], gold[gidx][59:56], gold[gidx][55:44],
                        gold[gidx][43:36], gold[gidx][35:20], gold[gidx][19:12],
                        gold[gidx][1], gold[gidx][0]);
                end
                gidx = gidx + 1;
            end
        end
    end
end

task drive_vector( input [79:0] v );
    begin
        cur_frame = v[79:60];
        exp_gate  = v[56];
        gate_seen = 0;
        @(negedge clk);
        addr      = v[54:32];
        dout      = v[31:16];
        dsn       = v[5:4];
        rnw       = v[1];
        cs        = v[0];
        drive_act = 1;
        repeat (6) @(negedge clk);
        // idle: strobes deasserted between bus cycles (68K guarantees this)
        dsn       = 2'b11;
        cs        = 1'b0;
        rnw       = 1'b1;
        drive_act = 0;
        repeat (6) @(negedge clk);
        if( gate_seen !== exp_gate ) begin
            errors = errors + 1;
            $display("FAIL %0s: gate=%b expected=%b at frame=%0d addr=%06x dout=%04x dsn=%b",
                     run_name, gate_seen, exp_gate, cur_frame,
                     {v[54:32],1'b0}, v[31:16], v[5:4]);
        end
        if( gate_seen ) gates_seen = gates_seen + 1;
    end
endtask

initial begin
    if( !$value$plusargs("NAME=%s", run_name) ) run_name = "run";
    if( !$value$plusargs("CFG=%s",  fname) ) begin
        $display("FAIL: +CFG missing"); $finish;
    end
    $readmemh(fname, cfg_mem);
    if( !$value$plusargs("TRIG=%s", fname) ) begin
        $display("FAIL: +TRIG missing"); $finish;
    end
    $readmemh(fname, trig_mem);
    if( !$value$plusargs("STIM=%s", fname) ) begin
        $display("FAIL: +STIM missing"); $finish;
    end
    $readmemh(fname, stim);
    if( !$value$plusargs("GOLD=%s", fname) ) begin
        $display("FAIL: +GOLD missing"); $finish;
    end
    $readmemh(fname, gold);
    if( $value$plusargs("VCD=%s", vcd_name) ) begin
        $dumpfile(vcd_name);
        $dumpvars(0, tb_trigger);
    end

    n_stim = 0;
    while( n_stim < MAX_STIM && stim[n_stim] !== 80'bx ) n_stim = n_stim + 1;
    n_gold = 0;
    while( n_gold < MAX_GOLD && gold[n_gold] !== 80'bx ) n_gold = n_gold + 1;

    errors = 0; gates_seen = 0; events_seen = 0; gidx = 0;
    drive_act = 0; exp_gate = 0; gate_seen = 0; cur_frame = 0;
    rst = 1; cfg_we = 0; trig_we = 0;
    addr = 0; dout = 0; dsn = 2'b11; rnw = 1; cs = 0;
    repeat (5) @(negedge clk);
    rst = 0;
    repeat (2) @(negedge clk);

    // load the trigger table through its write port
    for( i = 0; i < TRIG_ROWS; i = i+1 ) begin
        trig_we   = 1;
        trig_addr = i[12:0];
        trig_data = trig_mem[i];
        @(negedge clk);
    end
    trig_we = 0;
    // load the protocol config through its write port
    for( i = 0; i < CFG_LINES; i = i+1 ) begin
        cfg_we   = 1;
        cfg_addr = cfg_mem[i][23:16];
        cfg_data = cfg_mem[i][15:0];
        @(negedge clk);
    end
    cfg_we = 0;
    repeat (6) @(negedge clk);   // let the lookup settle post-load

    for( i = 0; i < n_stim; i = i+1 )
        drive_vector( stim[i] );

    repeat (10) @(negedge clk);

    if( gidx !== n_gold ) begin
        errors = errors + 1;
        $display("FAIL %0s: %0d events emitted, %0d expected",
                 run_name, gidx, n_gold);
    end
    if( err_unsettled ) begin
        errors = errors + 1;
        $display("FAIL %0s: err_unsettled asserted", run_name);
    end
    if( errors == 0 )
        $display("PASS %0s: vectors=%0d events=%0d gates=%0d",
                 run_name, n_stim, events_seen, gates_seen);
    else
        $display("RESULT %0s: %0d ERRORS", run_name, errors);
    $finish;
end

endmodule
